/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import model.gui.main.Cell;
import resources.images.ImageInstance;
import service.gui.MainService;
import service.gui.impl.MainServiceImpl;
import territory.Territory;
import thread.main.MainThread;

/**
 *
 * @author User
 */
public class Main extends javax.swing.JFrame {
    
    private MainService mainService = new MainServiceImpl();
    public static Cell selectedCell = null;
    public static Cell selectedAction = null;
    private MainThread thread = new MainThread();
    private Territory territory;
    
    public Main(Territory territory) {
        this.territory = territory;
        initComponents();
        this.setIconImage(ImageInstance.getDefault());
        mainService.mapInit(this.map);
        mainService.mapActions(buildings);
        mainService.mapResources(resources, territory.getResources());
        thread.start();
    }
    
    public void createBuilding(Cell place, Cell selected){
        mainService.setImage(place, selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        map = new javax.swing.JPanel();
        actionsPanel = new javax.swing.JPanel();
        actions = new javax.swing.JTabbedPane();
        buildings = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        resources = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Knights of the Nights");
        setMaximumSize(new java.awt.Dimension(1100, 662));
        setMinimumSize(new java.awt.Dimension(1100, 662));

        map.setMaximumSize(new java.awt.Dimension(640, 640));
        map.setPreferredSize(new java.awt.Dimension(640, 640));
        map.setLayout(null);

        javax.swing.GroupLayout buildingsLayout = new javax.swing.GroupLayout(buildings);
        buildings.setLayout(buildingsLayout);
        buildingsLayout.setHorizontalGroup(
            buildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        buildingsLayout.setVerticalGroup(
            buildingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        actions.addTab("Buildings", buildings);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        actions.addTab("tab2", jPanel2);

        javax.swing.GroupLayout resourcesLayout = new javax.swing.GroupLayout(resources);
        resources.setLayout(resourcesLayout);
        resourcesLayout.setHorizontalGroup(
            resourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        resourcesLayout.setVerticalGroup(
            resourcesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        actions.addTab("Resources", resources);

        javax.swing.GroupLayout actionsPanelLayout = new javax.swing.GroupLayout(actionsPanel);
        actionsPanel.setLayout(actionsPanelLayout);
        actionsPanelLayout.setHorizontalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actions)
                .addContainerGap())
        );
        actionsPanelLayout.setVerticalGroup(
            actionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actions)
                .addContainerGap())
        );

        actions.getAccessibleContext().setAccessibleName("Buildings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(map, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(actionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(map, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane actions;
    private javax.swing.JPanel actionsPanel;
    private javax.swing.JPanel buildings;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel map;
    private javax.swing.JPanel resources;
    // End of variables declaration//GEN-END:variables
}
